---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-infra-config
  namespace: minio-infra
spec:
  encryptedData:
    config.env: AgAKa31Vkk6RSqWj+D/nEClAJs4G25AVIt/dt/r8ZAbTP3bwZKsVqURmB8y7etR7omJ+6gZ6PP5+K0CAutdVBJIfEpPZ7qhCp/Xzx07Z1hra9qX3OFpzYj38KnAxgo9u+hAVj+hX0lOSaIFdHKMEjsWy8Fe09r4OLLyH1Y/CEfCvYXenAY/k+Qr4twEjyCSqkoIU3SYtZK5m9mS244ca8/QOP1sruA35pNBbmvHaPdzV5xnFLz3jrNmotDoZ6yVAsznBHP6vPDIs+INn0KavtAKFqeDY/mZH+d+V6pCesCliv38rVIiP1+wMOsAe0e8UmDDL0Kg58+c9NnIpgm5k3kK6u0kEcTLCTMAzBsZFrk2KAXW1A0Z5Wr9utTpBOeBcHyUgP+HJTv+XQxNGIfLw5INY7J5lY4R06AQ74KWI3Rsgi4J4TYRTfv6EfBQdPtOrGK6fvIAwryXi7VGNk885MKytROGcuLuQ9LLKMUG2Gi0NN6OV2RLYDRzAJhlOK9acsnisZdziZ2WXbp4tTJ3660n44CQt+iIaCEhimvyaLjkn6Qq1Oz12E65Zt/oGW1RjwJJqkJeWhbWsmJkLEIQG8+xPEiSFpGXmIytZH2dipzBZrpBKwjLw60pDD+cVGCcSUnfgt6Poqil80uRiCMqd+SeYCofxofcc0QjbAl77+3nikB5QUWcGtdtmV8Smm1LnrrjrWoHP9q/MC9Bn7P56HVtscOZN8/WcC+3zEn8iQJtfLKeCsNW9IM32JIZI+8t8k9oMrvGkQ+Hx+DAmrgiRIMfbmumcsZVKRD8uvyHAiHu/B0+AkSI6y7unppTRykwDA5teU0kGHsHPvK/NfM95FuBEmlIbJA==
  template:
    metadata:
      name: minio-infra-config
      namespace: minio-infra
