---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-secrets
  namespace: minecraft-system
spec:
  encryptedData:
    cf-api-key: AgBFQs5XQSppRcCeh1pRO8M+YzDs+hiT1zmM0E5X6ttDRTuGecB84Nav5GxZnA60heGjia2b9lxzytroWRp48yuu+sLqjzXNHAdU+h0SARkKhBTeZezKaoZANTzYbagySgdl9/LbCl4dEIQIrRGNHp5zlgV6xbtBKU1SOSBK5vXfflWweWdmg3Lu2vpaxIWFlGiamja8oVunwGZobRGoHU0+vUnraxdOzuQj7cCmj3qkCCnS8wx4menYBAATJ0XaatqRgpWQAMcupQ+GOy7Ead3QvDaEsf1bykXLcGut5rK8Bn0LWCCrP1iTDTyx4aT6n3ToTywfk7Ld4OwvTffF0pJ1FlDjvmP/B1pfK3pnH5IbW3arIO2ZZbSodEwlUJklCotiD+TmmHS2SMUEBA3RGjn4h6FBKp+jy3/e7R+QUih1Rq6H34YFflV0EsD8VUb7btahLqBvUypfIRjToh+/e12QjejYLY0lgRRgjzu5JDmtJQ7erR/eul1WntOHx3F0dHH2uA+aP67g1IzYBgkw98Vsnz6ddbsTzrNPT/zat/A7Rn3II77kqbwOu1V6dHYbH/kshCWZHKBVHVemgBs0TOC2QpAekBUraN+LvtDiOGkSLqj8Jx1aiinm5QCuvxOIczxG+PcNL/pvRr3lQN9zJpHY5HMPi/9Ec1U+oLpAfCXJBo/YH5IWbQeO3oZNBBYgHSCr8De+22c3VfZALHWVL8onNYoI7dmVlNwgaeUTp4lKAUFhWX4vv8WG1KNePbjXOh0D7Ne0PUsYMo6LOHg=
    rcon-password: AgBGweHMdcMVrDzhvtfcWKyH8WEKUqSEmJ/ZOCjrhdmMa680PeXXfcltUa11MPop3tDnxYz9lUUlmnsJe4iZN6LEOUBclCGNt9RWi2XoIsX0+aeMPEr8VCJnhlthLK8A957/x553AA0POGNq0a+YBDUGRdN1lava/WKMJME6aqegkPcad4Kjf24uphudT4rJD0xg1S6/wsSMhitoSgnUI5SJvrrRa87r5nGFu2MWfPUelahYw7FfrhJXbPeHOfrlYUGCTjEIzvCNBc16N4t7OKqx1RvllIwY5ux2pyHEBZmxlJiOd+zgDbCR+G29M/OcfIpL0B/nn4mUUAHboxiQOBIRq+QSTRk0L2U73JYEXrumXifXiaA2haJNZTqWACas8TpDPJkxAeWETKqTzaH0p64UlYGbqhr9po0mUGqEiFUwj+2FpueB/MvieKeVxg60gRLGOn8grIb4X6AEpGqf1U7ltYFuGiAiTna6PoZfmpRfOLKikWVGx4vRyy7CQjnJ0hxaxLyZ6/oN31mg354ja/Bdw9Zc/lQChJnGa10kxtrOE68QPFAUTUudhEDygxm8xl+lu7YNHxJuqpUfmbdatYoX7U1pawCO4TnbmCTttWSmKDxeVanp6W7i91S5jekC4L+NuqNyaGZXFRARzCRtaVlsX+5rhLXp83+gL8OBkiDWnOvYVTvgg353+V7CLhSzTC6A2aRLBBkUDInUQoIC83Fhu7cVcxdGfu3xx/Y3z28qYQpgv7f3TY/eWsJ9AtF1QHI=
  template:
    type: Opaque
    metadata:
      name: minecraft-secrets
      namespace: minecraft-system
