apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fire-prod-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.ops.last-try.org/lt/fire/envs.git
    targetRevision: master
    path: prod/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: fire-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
